Repository facebook/usort, pull requests merged in 2022-09, with the labels that each got.

#195 Avoid KeyError when imports are duplicated.
  setup.cfg
  usort/sorting.py
  usort/tests/__init__.py
  usort/tests/functional.py
  usort/tests/sorting.py
Labels: CLA Signed

#154 PEP 621 project metadata
  .flake8
  .github/workflows/build.yml
  Makefile
  pyproject.toml
  setup.cfg
  setup.py
Labels: CLA Signed, deferred

#204 Treat lines with multiple statements as barriers
  docs/guide.rst
  usort/sorting.py
  usort/tests/functional.py
  usort/translate.py
Labels: bug, CLA Signed

#205 Script and CI action to validate backwards compatibility
  .github/workflows/build.yml
  Makefile
  check_backcompat.py
Labels: CLA Signed

#148 Versioning Guide
  MAINTAINERS.md
  docs/api.rst
  docs/changelog.rst
  docs/index.rst
  docs/versioning.rst
  pyproject.toml
Labels: documentation, CLA Signed
