Repository facebook/usort, pull requests merged in 2022-01, with the labels that each got.

#126 Remove or defer use of PositionProvider metadata when sorting
  usort/sorting.py
Labels: CLA Signed

#129 Fix #128: handle single line from-imports with parens
  usort/tests/functional.py
  usort/translate.py
Labels: bug, CLA Signed

#131 Update copyright, docs, logo with Meta name/logo
  LICENSE
  check_copyright.sh
  docs/_static/custom.css
  docs/_static/opensource.png
  docs/_templates/meta.html
  docs/conf.py
  setup.py
  usort/__init__.py
  usort/__main__.py
  usort/api.py
  usort/cli.py
  usort/config.py
  usort/sorting.py
  usort/stdlibs.py
  usort/tests/__init__.py
  usort/tests/__main__.py
  usort/tests/cli.py
  usort/tests/config.py
  usort/tests/functional.py
  usort/tests/stdlibs.py
  usort/tests/translate.py
  usort/tests/types.py
  usort/tests/util.py
  usort/translate.py
  usort/types.py
  usort/util.py
Labels: documentation, CLA Signed

#130 Add "why µsort" page to docs, update readme
  README.md
  docs/guide.rst
  docs/index.rst
  docs/why.rst
Labels: documentation, CLA Signed
